[[GraphicsMagick]]
arch = "aarch64"
git-tree-sha1 = "57636ce3895a1b864e5c5a126cfc07199004720c"
os = "macos"

    [[GraphicsMagick.download]]
    sha256 = "542c8a89f468f97ee9ecbf8153ee0716daa26f3773264086810f0021a082f235"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.aarch64-apple-darwin.tar.gz"
[[GraphicsMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02dc29471ebd9a6c8810d15fcc61aeb85ca17dfd"
libc = "glibc"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "fd2e85102c6d4140dfce1ab81cd28dd7133ee19d7615e3830b3e9736e2de0292"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.aarch64-linux-gnu-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5dba816077673fa4de14fec96f344d46e76571f"
libc = "musl"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "5f889d2c6c84b38cc91e8322f927533f18a2ff082d9b24e4145591bb3c8fa117"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.aarch64-linux-musl-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "aarch64"
git-tree-sha1 = "3d06dcc3bf6f58a806b0a7ab41d99d95b3ec8060"
os = "freebsd"

    [[GraphicsMagick.download]]
    sha256 = "ce5e9f1486b50def42af0edf7642f4f2231fa0233d948625e2fa463316a15c45"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.aarch64-unknown-freebsd.tar.gz"
[[GraphicsMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54c14c22688a40d6f8cd2cfe0858ec4fcf610678"
libc = "glibc"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "3e922783e6fefd71f8ae51607c2f0d52efce6b14535b9eeac08b478293513345"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36225953395dcf155dcac5d2ca47d537b0dadba4"
libc = "musl"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "e8f9ff808149b6426d2390009c5f1e159b727ce44dd60fe08812e8faae4c37aa"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2be1a7932faf43069c79de3e425228d91c776e07"
libc = "glibc"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "2ac20217e1e2f2eb0e0afd3f2d08d9128f3e2a3715e67a60318f98068082cb21"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db5020aa38847d6aa0280c8ac3aabfb14bccd14d"
libc = "musl"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "a8b3c28d0c5e991a8997782e1239c371ab6f454ae41dcb52ead24912db62f21a"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "469591134a35097b1a4f5fb96e232dd8eb9b9d4e"
libc = "glibc"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "5d6a606f1d9084ca8917f6d2b10cf0581514ba3790c624e723d3712f4bc916d8"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.i686-linux-gnu-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91c5cb3ec122146dc85e1b4fbe549fbc1877e499"
libc = "musl"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "b6cb819359409be7e752744b00a6b71d38697ac69b9996fb244d40347c3e796d"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.i686-linux-musl-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3aaa16a1e20f4485ab4f0d71235f0a44f7fa193"
os = "windows"

    [[GraphicsMagick.download]]
    sha256 = "0d56da408298ed4adad4fc015dc5f7a8b56c2f040798d1f4ca013240c178c9dd"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.i686-w64-mingw32-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50b4a425c7a77fcfb82137c610e55d1dd031b67d"
libc = "glibc"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "36040910e3fa6cef117a3df289c9d487debb4f9e7c04bcf9a6dc55b3543df0df"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c09e7e05f8f22c69b5f6e11f52449d646759c71f"
libc = "glibc"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "0a6bc5427ef23944b4f6153ae069fb27c599d312b2b5001a0ff4b9e3efbb883d"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.riscv64-linux-gnu-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "x86_64"
git-tree-sha1 = "6287175d9b7d3d001c9f3c6c83d07a33190f1454"
os = "macos"

    [[GraphicsMagick.download]]
    sha256 = "718d56798ce1d8f43a323a6055701d31791adec90baffa110425eab6d13d1b8f"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.x86_64-apple-darwin.tar.gz"
[[GraphicsMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d08605aac9684a6cd548c02a0dba6dafb8573fc8"
libc = "glibc"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "b0a9a4faee83617ac3e22b6580d4a8ac50f7dbc8b858a0cf7f22efc50c8991c5"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.x86_64-linux-gnu-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55d1656e824bbe0ff7252d7498611f436c48bbef"
libc = "musl"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "0d2fcfa9bba27d860c0c6c8c86f4191bad1d232a1be5e3587584111e9d50dcb2"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.x86_64-linux-musl-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "x86_64"
git-tree-sha1 = "0fdd012b3698b8729977d4270e244c0ae99dc263"
os = "freebsd"

    [[GraphicsMagick.download]]
    sha256 = "98233622469e3e73da07f9ee58320b9718cf5adfb5366660b38744d7f4f53cbb"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.x86_64-unknown-freebsd.tar.gz"
[[GraphicsMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbe19af906ada4ab66b0e04154d64589079382ed"
os = "windows"

    [[GraphicsMagick.download]]
    sha256 = "4f39fb105f8d145a078fa026390c1b8e6017b91c681b2b730ebe1cc4330ac428"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.47+0/GraphicsMagick.v1.3.47.x86_64-w64-mingw32-cxx11.tar.gz"
