name = "GraphicsMagick_jll"
uuid = "aa65733b-c888-5e24-8545-c87abc10c960"
version = "1.3.47+0"

[deps]
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
JpegTurbo_jll = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
libwebp_jll = "c5f90fcd-3b7e-5836-afba-fc50a0988cb2"
FreeType2_jll = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
Libtiff_jll = "89763e89-9b03-5906-acba-b20f662cd828"
JasPer_jll = "f6ca3df5-1ae7-521a-b96b-cb83f57f3f1f"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Bzip2_jll = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
XML2_jll = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
libpng_jll = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
Graphviz_jll = "3c863552-8265-54e4-a6dc-903eb78fde85"
XZ_jll = "ffd25f8a-64ca-5728-b0f7-c24cf3aae800"
Zstd_jll = "3161d3a3-bdf6-5164-811a-617609db77b4"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
Bzip2_jll = "1.0.9"
XML2_jll = "~2.13.6"
FreeType2_jll = "2.13.4"
libwebp_jll = "1.6.0"
Libdl = "< 0.0.1, 1"
Libtiff_jll = "4.7.2"
Artifacts = "< 0.0.1, 1"
